export const CHOOSE_ID = 'CHOOSE_ID'
export const SET_MAP_LOAD_STATE = 'SET_MAP_LOAD_STATE'
export const SET_QUERY_PARAMES = 'SET_QUERY_PARAMES'
export const SET_RESULT_PARAMES = 'SET_RESULT_PARAMES'

export const SET_PANEL_STATE = 'SET_PANEL_STATE'
